[[positions]]
id = "DTTC_FMP"
prefixes = ["DTTC"]
frequency = "132.500"
facility_type = "FMP"
profile_id = "DTTC"

[[positions]]
id = "DTTC_CTR"
prefixes = ["DTTC"]
frequency = "132.500"
facility_type = "CTR"
profile_id = "DTTC"

[[positions]]
id = "DTTC_I_CTR"
prefixes = ["DTTC"]
frequency = "128.900"
facility_type = "CTR"
profile_id = "DTTC"

[[positions]]
id = "DTTC_N_CTR"
prefixes = ["DTTC"]
frequency = "132.550"
facility_type = "CTR"
profile_id = "DTTC-NORTH"

[[positions]]
id = "DTTC_S_CTR"
prefixes = ["DTTC"]
frequency = "129.300"
facility_type = "CTR"
profile_id = "DTTC-SOUTH"

[[positions]]
id = "DTTC_U_CTR"
prefixes = ["DTTC"]
frequency = "129.500"
facility_type = "CTR"
profile_id = "DTTC-NORTH"

[[positions]]
id = "DTKA_APP"
prefixes = ["DTKA"]
frequency = "125.150"
facility_type = "APP"

[[positions]]
id = "DTKA_TWR"
prefixes = ["DTKA"]
frequency = "119.250"
facility_type = "TWR"

[[positions]]
id = "DTNH_APP"
prefixes = ["DTNH"]
frequency = "119.300"
facility_type = "APP"

[[positions]]
id = "DTNH_TWR"
prefixes = ["DTNH"]
frequency = "118.550"
facility_type = "TWR"

[[positions]]
id = "DTNH_GND"
prefixes = ["DTNH"]
frequency = "121.670"
facility_type = "GND"

[[positions]]
id = "DTTA_APP"
prefixes = ["DTTA"]
frequency = "121.200"
facility_type = "APP"
profile_id = "DTTA"

[[positions]]
id = "DTTA_U_APP"
prefixes = ["DTTA"]
frequency = "119.500"
facility_type = "APP"
profile_id = "DTTA"

[[positions]]
id = "DTTA_TWR"
prefixes = ["DTTA"]
frequency = "118.100"
facility_type = "TWR"
profile_id = "DTTA"

[[positions]]
id = "DTTA_GND"
prefixes = ["DTTA"]
frequency = "121.900"
facility_type = "GND"
profile_id = "DTTA"

[[positions]]
id = "DTTA_DEL"
prefixes = ["DTTA"]
frequency = "130.675"
facility_type = "DEL"
profile_id = "DTTA"

[[positions]]
id = "DTTF_APP"
prefixes = ["DTTF"]
frequency = "122.750"
facility_type = "APP"

[[positions]]
id = "DTTF_TWR"
prefixes = ["DTTF"]
frequency = "125.100"
facility_type = "TWR"

[[positions]]
id = "DTTG_APP"
prefixes = ["DTTG"]
frequency = "129.150"
facility_type = "APP"

[[positions]]
id = "DTTG_TWR"
prefixes = ["DTTG"]
frequency = "119.150"
facility_type = "TWR"

[[positions]]
id = "DTTJ_APP"
prefixes = ["DTTJ"]
frequency = "120.300"
facility_type = "APP"

[[positions]]
id = "DTTJ_TWR"
prefixes = ["DTTJ"]
frequency = "118.150"
facility_type = "TWR"

[[positions]]
id = "DTTX_APP"
prefixes = ["DTTX"]
frequency = "123.700"
facility_type = "APP"

[[positions]]
id = "DTTX_TWR"
prefixes = ["DTTX"]
frequency = "120.150"
facility_type = "TWR"

[[positions]]
id = "DTTZ_APP"
prefixes = ["DTTZ"]
frequency = "120.700"
facility_type = "APP"

[[positions]]
id = "DTTZ_TWR"
prefixes = ["DTTZ"]
frequency = "118.200"
facility_type = "TWR"

[[positions]]
id = "DTMB_TWR"
prefixes = ["DTMB"]
frequency = "118.300"
facility_type = "TWR"

[[positions]]
id = "DTTI_TWR"
prefixes = ["DTTI"]
frequency = "123.000"
facility_type = "TWR"
profile_id = "DTTI"
